#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"

need_bin jq

ensure_veil_dir
ensure_sdk

HAS_FORCE=false
for arg in "$@"; do [[ "$arg" == "--force" ]] && HAS_FORCE=true; done

if [[ -f "$VEIL_ENV" ]]; then
  echo "Veil env already exists: $VEIL_ENV" >&2
  echo "(delete it to regenerate, or pass --force)" >&2
  if [[ "$HAS_FORCE" != "true" ]]; then
    exit 0
  fi
  echo "Overwriting (--force)..." >&2
fi

# Generate keypair as JSON and write to env file
# (--force is harmless to the CLI in --json mode)
KP_JSON=$(veil_cli init --json "$@")

VEIL_KEY=$(echo "$KP_JSON" | jq -r '.veilKey')
DEPOSIT_KEY=$(echo "$KP_JSON" | jq -r '.depositKey')

if [[ -z "$VEIL_KEY" || "$VEIL_KEY" == "null" ]]; then
  echo "Failed to generate keypair" >&2
  echo "$KP_JSON" >&2
  exit 1
fi

cat > "$VEIL_ENV" << EOF
# Veil Cash Configuration
# Generated by: veil-init.sh
VEIL_KEY=$VEIL_KEY
DEPOSIT_KEY=$DEPOSIT_KEY
EOF

chmod 600 "$VEIL_ENV"
echo "Wrote: $VEIL_ENV" >&2
